# Extract URLs from JSON "text" fields and fetch DOI links

Author: Corentin Briat
* Made to scrape papers from the Seminar on Biological Control Systems Slack

This notebook:
1. Recursively scans all `.json` files under `ROOT_DIR`.
2. Extracts URLs from each JSON object's `text` field into a pandas DataFrame.
3. Fetches each URL and tries to detect DOI(s) (doi.org links or DOI strings) and stores them in the DataFrame.

## 0) Set directory
Set `ROOT_DIR` to the directory containing your JSON files (Slack-export-like).

In [1]:
from pathlib import Path

# EDIT THIS:
ROOT_DIR = Path("./").expanduser().resolve()

ROOT_DIR, ROOT_DIR.exists()

(PosixPath('/Users/corentinbriat/Downloads/Seminar on Biological Control Systems Slack export Jun 28 2021 - Jan 12 2026/papers'),
 True)

## 1) Imports

If you don't have BeautifulSoup installed, run the install cell.

In [1]:
# If needed:
# !pip install requests beautifulsoup4 lxml pandas

import json
import re
import time
from typing import Dict, Iterable, List, Optional, Tuple

import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse

## 2) URL extraction from text

Supports Slack link markup:
- `<https://example.com|label>`
- `<https://example.com>`

and plain URLs.

In [3]:
SLACK_LINK_RE = re.compile(r"<(https?://[^>|]+)(?:\|[^>]+)?>")
PLAIN_URL_RE = re.compile(r"(https?://[^\s<>()\"']+)", re.IGNORECASE)
TRAILING_PUNCT = ".,;:!?)\u2019\u201d\"'"

def extract_urls_from_text(text: str) -> List[str]:
    if not text or not isinstance(text, str):
        return []
    urls: List[str] = []
    urls.extend(m.group(1) for m in SLACK_LINK_RE.finditer(text))
    urls.extend(m.group(1) for m in PLAIN_URL_RE.finditer(text))
    cleaned = [u.rstrip(TRAILING_PUNCT) for u in urls]
    # Dedupe while preserving order
    seen = set()
    out = []
    for u in cleaned:
        if u not in seen:
            seen.add(u)
            out.append(u)
    return out

# extract_urls_from_text("<https://doi.org/10.1038/s41587-021-00950-3|doi>")

## 3) Scan JSON files and build DataFrame of URL hits

Assumes each `.json` file is a list of dicts (messages). Extracts URLs from each dict's `text` field.

In [4]:
def iter_json_files(root: Path) -> Iterable[Path]:
    if root.is_file() and root.suffix.lower() == ".json":
        yield root
        return
    for p in root.rglob("*.json"):
        if p.is_file():
            yield p

def load_json(path: Path):
    try:
        txt = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        txt = path.read_text(encoding="latin-1")
    return json.loads(txt)

rows = []
for jf in iter_json_files(ROOT_DIR):
    try:
        data = load_json(jf)
    except Exception:
        continue
    if not isinstance(data, list):
        continue
    for i, item in enumerate(data):
        if not isinstance(item, dict):
            continue
        text = item.get("text", "")
        urls = extract_urls_from_text(text)
        for u in urls:
            rows.append({
                "url": u,
                "file": str(jf),
                "message_index": i,
                "ts": str(item.get("ts", "")),
                "user": str(item.get("user", "")),
            })

df_urls = pd.DataFrame(rows)
df_urls.head(), len(df_urls), df_urls["url"].nunique()

(                                                 url  \
 0                   https://arxiv.org/abs/2409.00034
 1  https://www.biorxiv.org/content/10.1101/2024.0...
 2  https://www.biorxiv.org/content/10.1101/2024.0...
 3  https://www.biorxiv.org/content/10.1101/2024.1...
 4  https://www.biorxiv.org/content/10.1101/2022.0...

                                                 file  message_index  \
 0  /Users/corentinbriat/Downloads/Seminar on Biol...              0
 1  /Users/corentinbriat/Downloads/Seminar on Biol...              0
 2  /Users/corentinbriat/Downloads/Seminar on Biol...              0
 3  /Users/corentinbriat/Downloads/Seminar on Biol...              0
 4  /Users/corentinbriat/Downloads/Seminar on Biol...              0

                   ts         user
 0  1725700424.044759  U029THP4J8Y
 1  1712677662.913899  U02684Y5BGW
 2  1712677662.913899  U02684Y5BGW
 3  1732997414.424169  U02684Y5BGW
 4  1643374186.531939  U02684Y5BGW  ,
 1106,
 1055)

In [5]:
DOI_RE = re.compile(r"\b10\.\d{4,9}/[-._;()/:A-Z0-9]+\b", re.IGNORECASE)

META_NAME_KEYS = {
    "citation_doi",
    "dc.identifier",
    "dc.identifier.doi",
    "prism.doi",
}
META_PROPERTY_KEYS = {
    "citation_doi",
    "prism:doi",
    "dc.identifier",
}

def normalize_doi(doi: str) -> str:
    doi = doi.strip()
    doi = doi.replace("doi:", "").replace("DOI:", "").strip()
    doi = doi.rstrip(".,;:!?)\"'")

    # Common preprint version suffix: ...v1, v2
    doi = re.sub(r"(10\.\d{4,9}/[^\s]+?)v\d+$", r"\1", doi, flags=re.IGNORECASE)
    return doi

def doi_to_link(doi: str) -> str:
    return f"https://doi.org/{doi}"

def dedupe_keep_order(seq: List[str]) -> List[str]:
    seen = set()
    out = []
    for x in seq:
        if x and x not in seen:
            seen.add(x)
            out.append(x)
    return out

def extract_dois_from_url(url: str) -> Tuple[List[str], List[str], str]:
    """Return (doi_links, dois, hint)."""
    if not url:
        return [], [], ""
    found = [normalize_doi(m.group(0)) for m in DOI_RE.finditer(url)]
    found = dedupe_keep_order([d for d in found if d])
    if found:
        return [doi_to_link(d) for d in found], found, "found_in_url"
    return [], [], ""

In [6]:
def make_session():
    s = requests.Session()
    s.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/122.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Connection": "keep-alive",
    })
    return s

session = make_session()

In [7]:
import json as _json

def extract_dois_from_html(html: str) -> Tuple[List[str], List[str], str]:
    doi_links = []
    dois = []
    hints = []

    soup = BeautifulSoup(html, "lxml")

    # ---- A) Meta tags (publisher-agnostic) ----
    for meta in soup.find_all("meta"):
        name = (meta.get("name") or "").strip().lower()
        prop = (meta.get("property") or "").strip().lower()
        content = (meta.get("content") or "").strip()

        if (name in META_NAME_KEYS) or (prop in META_PROPERTY_KEYS):
            for m in DOI_RE.finditer(content):
                d = normalize_doi(m.group(0))
                if d:
                    dois.append(d)
                    doi_links.append(doi_to_link(d))
                    hints.append("found_in_meta")

    # ---- B) doi.org links ----
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if "doi.org/" in href.lower():
            m = re.search(r"doi\.org/(.+)$", href, re.IGNORECASE)
            if m:
                d = normalize_doi(m.group(1))
                if d:
                    dois.append(d)
                    doi_links.append(doi_to_link(d))
                    hints.append("found_in_doi_link")

    # ---- C) JSON-LD (Nature often includes DOI here) ----
    for script in soup.find_all("script", attrs={"type": "application/ld+json"}):
        try:
            txt = script.string or script.get_text() or ""
            txt = txt.strip()
            if not txt:
                continue
            data = _json.loads(txt)

            # JSON-LD can be dict or list; normalize to list
            items = data if isinstance(data, list) else [data]

            for obj in items:
                if not isinstance(obj, dict):
                    continue

                # Common schema keys where DOI may appear
                # identifier can be dict or list; same for isPartOf, mainEntity, etc.
                candidates = []

                # direct fields
                for k in ["doi", "DOI", "identifier", "sameAs", "url"]:
                    if k in obj:
                        candidates.append(obj[k])

                # walk nested structures lightly
                for k in ["mainEntity", "isPartOf", "about"]:
                    if k in obj:
                        candidates.append(obj[k])

                # flatten candidates to strings
                def walk(x):
                    if isinstance(x, str):
                        yield x
                    elif isinstance(x, dict):
                        for v in x.values():
                            yield from walk(v)
                    elif isinstance(x, list):
                        for v in x:
                            yield from walk(v)

                for s in walk(candidates):
                    # capture doi.org or raw DOI
                    if "doi.org/" in s.lower():
                        m = re.search(r"doi\.org/(.+)$", s, re.IGNORECASE)
                        if m:
                            d = normalize_doi(m.group(1))
                            if d:
                                dois.append(d)
                                doi_links.append(doi_to_link(d))
                                hints.append("found_in_jsonld")
                    else:
                        for m in DOI_RE.finditer(s):
                            d = normalize_doi(m.group(0))
                            if d:
                                dois.append(d)
                                doi_links.append(doi_to_link(d))
                                hints.append("found_in_jsonld")
        except Exception:
            # ignore broken JSON-LD blocks
            continue

    # ---- D) Nature-specific / plain text fallback ----
    # If DOI appears as plain text (e.g., "https://doi.org/..." absent),
    # searching visible text helps.
    if not dois:
        text = soup.get_text(" ", strip=True)
        for m in DOI_RE.finditer(text):
            d = normalize_doi(m.group(0))
            if d:
                dois.append(d)
                doi_links.append(doi_to_link(d))
                hints.append("found_in_visible_text")
                break  # usually one DOI is enough

    # ---- E) Regex over raw HTML as final catch-all ----
    if not dois:
        for m in DOI_RE.finditer(html):
            d = normalize_doi(m.group(0))
            if d:
                dois.append(d)
                doi_links.append(doi_to_link(d))
                hints.append("found_by_regex")
                break

    doi_links = dedupe_keep_order(doi_links)
    dois = dedupe_keep_order(dois)
    hints = dedupe_keep_order(hints)

    return doi_links, dois, ";".join(hints)

In [8]:
def is_arxiv(url: str) -> bool:
    host = (urlparse(url).netloc or "").lower()
    return "arxiv.org" in host

def fetch_html_limited(resp: requests.Response, max_bytes: int = 200_000_000) -> str:
    content = b""
    for chunk in resp.iter_content(chunk_size=8192):
        if not chunk:
            break
        content += chunk
        if len(content) >= max_bytes:
            break
    try:
        return content.decode("utf-8", errors="ignore")
    except Exception:
        return content.decode("latin-1", errors="ignore")

def fetch_and_find_dois(url: str,
                        session: requests.Session,
                        timeout: float = 20,
                        max_bytes: int = 200_000_000,
                        sleep_s: float = 0.0) -> Dict[str, object]:

    out = {
        "url": url,
        "http_status": None,
        "final_url": "",
        "doi_links": "",
        "dois": "",
        "source_hint": "",
        "fetch_error": "",
    }

    doi_links, dois, hint = extract_dois_from_url(url)
    hints = [hint] if hint else []

    try:
        r = session.get(url, allow_redirects=True, timeout=timeout, stream=True)
        out["http_status"] = int(r.status_code)
        out["final_url"] = str(r.url)

        # DOI from final URL too
        dl2, d2, hint2 = extract_dois_from_url(out["final_url"])
        doi_links += dl2
        dois += d2
        if hint2:
            hints.append(hint2)

        if out["http_status"] == 403:
            out["fetch_error"] = "403 Forbidden (site may block automated requests)"
        else:
            html = fetch_html_limited(r, max_bytes=max_bytes)
            dl3, d3, hint3 = extract_dois_from_html(html)
            doi_links += dl3
            dois += d3
            if hint3:
                hints.append(hint3)

        r.close()

    except Exception as e:
        out["fetch_error"] = str(e)

    doi_links = dedupe_keep_order(doi_links)
    dois = dedupe_keep_order(dois)

    # If arXiv and no DOI, label it (arXiv often has none)
    if is_arxiv(url) and not dois:
        hints.append("arxiv_no_doi_expected")

    out["doi_links"] = ",".join(doi_links)
    out["dois"] = ",".join(dois)
    out["source_hint"] = ",".join(dedupe_keep_order([h for h in hints if h]))

    if sleep_s:
        time.sleep(sleep_s)

    return out

In [9]:
session = make_session()

nature_url = "https://www.nature.com/articles/s41467-024-46755-1"
res = fetch_and_find_dois(nature_url, session=session, sleep_s=0.0)
res

{'url': 'https://www.nature.com/articles/s41467-024-46755-1',
 'http_status': 200,
 'final_url': 'https://www.nature.com/articles/s41467-024-46755-1',
 'doi_links': 'https://doi.org/10.1038/s41467-024-46755-1,https://doi.org/10.15252%2Fmsb.20145735,https://doi.org/10.1126%2Fscience.aac7341,https://doi.org/10.1038%2Fncomms15459,https://doi.org/10.1038%2Fs41467-019-12706-4,https://doi.org/10.1038%2Fs41467-020-18302-1,https://doi.org/10.1038%2Fs41587-020-0468-5,https://doi.org/10.1126%2Fscience.1067407,https://doi.org/10.1016%2Fj.cell.2011.01.030,https://doi.org/10.1038%2Fs41589-018-0168-3,https://doi.org/10.1038%2Fnmeth.4505,https://doi.org/10.3389%2Ffbioe.2019.00080,https://doi.org/10.1038%2Fs41467-020-17993-w,https://doi.org/10.1021%2Facssynbio.5b00286,https://doi.org/10.1038%2Fmsb.2008.24,https://doi.org/10.1038%2Fs41467-018-05046-2,https://doi.org/10.15252%2Fmsb.20209618,https://doi.org/10.1073%2Fpnas.1202344109,https://doi.org/10.1126%2Fscience.1232758,https://doi.org/10.1038%2Fnbt.2510,https://doi.org/10.1038%2Fnmeth.3147,https://doi.org/10.1126%2Fscience.1256272,https://doi.org/10.1126%2Fscience.aad8559,https://doi.org/10.1038%2Fnbt.3805,https://doi.org/10.1126%2Fscience.1172005,https://doi.org/10.1126%2Fscience.aap8992,https://doi.org/10.1016%2Fj.jmb.2018.09.007,https://doi.org/10.1042%2FBJ20151112,https://doi.org/10.1016%2FS1097-2765%2803%2900444-1,https://doi.org/10.1046%2Fj.1365-2958.2000.01720.x,https://doi.org/10.1038%2Fs41467-020-18455-z,https://doi.org/10.1371%2Fjournal.pone.0002815,https://doi.org/10.1038%2Fs41467-021-22978-4,https://doi.org/10.1021%2Fsb3000595,https://doi.org/10.1038%2Fnchembio.1680,https://doi.org/10.1038%2Fs41565-017-0004-z,https://doi.org/10.1038%2Fsrep09015,https://doi.org/10.1073%2Fpnas.1508521112,https://doi.org/10.1126%2Fscitranslmed.aaa3601,https://doi.org/10.1038%2Fs41467-023-41043-w,https://doi.org/10.1073%2Fpnas.2111450118,https://doi.org/10.1038%2Fs41467-022-31614-8,https://doi.org/10.1038%2Fs41564-020-0757-2,https://doi.org/10.1038%2Fnbt.1568,https://doi.org/10.1016%2Fj.molcel.2016.06.006,https://doi.org/10.1038%2Fs41467-019-08391-y,https://doi.org/10.1016%2Fj.cels.2015.06.001,https://doi.org/10.1021%2Facssynbio.7b00328,https://doi.org/10.1038%2Fs41467-020-18630-2,https://doi.org/10.1093%2Fnar%2Fgkaa734,https://doi.org/10.1038%2Fnmeth.3339,https://doi.org/10.1016%2Fj.mib.2018.02.009,https://doi.org/10.1021%2Facssynbio.8b00284,https://doi.org/10.1038%2Fnrmicro.2017.172,https://doi.org/10.1021%2Facssynbio.6b00361,https://doi.org/10.1021%2Facssynbio.6b00040,https://doi.org/10.1038%2Fs41467-018-02898-6,https://doi.org/10.1093%2Fnar%2Fgkv1280,https://doi.org/10.15252%2Fmsb.20209584,https://doi.org/10.1016%2Fj.cels.2023.05.004,https://doi.org/10.1038%2Fhdy.2010.24,https://doi.org/10.1038%2F35012500,https://doi.org/10.1093%2Fgenetics%2F155.4.1505,https://doi.org/10.1038%2Fnmeth.2515,https://doi.org/10.1038%2Fncomms3503,https://doi.org/10.1101/110254,https://doi.org/10.1016%2Fj.cell.2013.02.022,https://doi.org/10.1021%2Facssynbio.6b00048,https://doi.org/10.1021%2Fja506664a,https://doi.org/10.1073%2Fpnas.120163297,https://doi.org/10.1371%2Fjournal.pone.0003647,https://doi.org/10.1038%2Fnmeth.1318,https://doi.org/10.1038/s41467-025-64457-0',
 'dois': '10.1038/s41467-024-46755-1,10.15252%2Fmsb.20145735,10.1126%2Fscience.aac7341,10.1038%2Fncomms15459,10.1038%2Fs41467-019-12706-4,10.1038%2Fs41467-020-18302-1,10.1038%2Fs41587-020-0468-5,10.1126%2Fscience.1067407,10.1016%2Fj.cell.2011.01.030,10.1038%2Fs41589-018-0168-3,10.1038%2Fnmeth.4505,10.3389%2Ffbioe.2019.00080,10.1038%2Fs41467-020-17993-w,10.1021%2Facssynbio.5b00286,10.1038%2Fmsb.2008.24,10.1038%2Fs41467-018-05046-2,10.15252%2Fmsb.20209618,10.1073%2Fpnas.1202344109,10.1126%2Fscience.1232758,10.1038%2Fnbt.2510,10.1038%2Fnmeth.3147,10.1126%2Fscience.1256272,10.1126%2Fscience.aad8559,10.1038%2Fnbt.3805,10.1126%2Fscience.1172005,10.1126%2Fscience.aap8992,10.1016%2Fj.jmb.2018.09.007,10.1042%2FBJ20151112,10.1016%2FS1097-2765%2803%2900444-1,10.1046%2Fj.1365-2958.2000.01720.x,10.1038%2Fs41467-020-18455-z,10.1371%2Fjournal.pone.0002815,10.1038%2Fs41467-021-22978-4,10.1021%2Fsb3000595,10.1038%2Fnchembio.1680,10.1038%2Fs41565-017-0004-z,10.1038%2Fsrep09015,10.1073%2Fpnas.1508521112,10.1126%2Fscitranslmed.aaa3601,10.1038%2Fs41467-023-41043-w,10.1073%2Fpnas.2111450118,10.1038%2Fs41467-022-31614-8,10.1038%2Fs41564-020-0757-2,10.1038%2Fnbt.1568,10.1016%2Fj.molcel.2016.06.006,10.1038%2Fs41467-019-08391-y,10.1016%2Fj.cels.2015.06.001,10.1021%2Facssynbio.7b00328,10.1038%2Fs41467-020-18630-2,10.1093%2Fnar%2Fgkaa734,10.1038%2Fnmeth.3339,10.1016%2Fj.mib.2018.02.009,10.1021%2Facssynbio.8b00284,10.1038%2Fnrmicro.2017.172,10.1021%2Facssynbio.6b00361,10.1021%2Facssynbio.6b00040,10.1038%2Fs41467-018-02898-6,10.1093%2Fnar%2Fgkv1280,10.15252%2Fmsb.20209584,10.1016%2Fj.cels.2023.05.004,10.1038%2Fhdy.2010.24,10.1038%2F35012500,10.1093%2Fgenetics%2F155.4.1505,10.1038%2Fnmeth.2515,10.1038%2Fncomms3503,10.1101/110254,10.1016%2Fj.cell.2013.02.022,10.1021%2Facssynbio.6b00048,10.1021%2Fja506664a,10.1073%2Fpnas.120163297,10.1371%2Fjournal.pone.0003647,10.1038%2Fnmeth.1318,10.1038/s41467-025-64457-0',
 'source_hint': 'found_in_meta;found_in_doi_link;found_in_jsonld',
 'fetch_error': ''}

In [10]:
# session = make_session()

nature_url = "https://www.cell.com/cell-systems/fulltext/S2405-4712%2816%2930040-0"
res = fetch_and_find_dois(nature_url, session=session, sleep_s=0.0)
res

{'url': 'https://www.cell.com/cell-systems/fulltext/S2405-4712%2816%2930040-0',
 'http_status': 403,
 'final_url': 'https://www.cell.com/cell-systems/fulltext/S2405-4712%2816%2930040-0',
 'doi_links': '',
 'dois': '',
 'source_hint': '',
 'fetch_error': '403 Forbidden (site may block automated requests)'}

In [12]:
FETCH_UNIQUE_ONLY = True
MAX_URLS = None   # set e.g. 100 for testing
SLEEP_S = 0.0     # set e.g. 0.2 if you want to be polite

if df_urls.empty:
    doi_df = pd.DataFrame(columns=["url","http_status","final_url","doi_links","dois","source_hint","fetch_error"])
else:
    urls = df_urls["url"].dropna().tolist()
    if FETCH_UNIQUE_ONLY:
        urls = pd.Series(urls).drop_duplicates().tolist()
    if MAX_URLS is not None:
        urls = urls[:MAX_URLS]

    results = [fetch_and_find_dois(u, session=session, sleep_s=SLEEP_S) for u in urls]
    doi_df = pd.DataFrame(results)

df_out = df_urls.merge(doi_df, on="url", how="left")
df_out.head()

# df_out.to_csv('./df_out.csv', index=False)

,url,file,message_index,ts,user,http_status,final_url,doi_links,dois,source_hint,fetch_error
0,https://arxiv.org/abs/2409.00034,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1725700424.044759,U029THP4J8Y,200.0,https://arxiv.org/abs/2409.00034,"https://doi.org/10.1021/acssynbio.5c00099,http...","10.1021/acssynbio.5c00099,10.48550/arXiv.2409....",found_in_meta;found_in_doi_link,
1,https://www.biorxiv.org/content/10.1101/2024.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1712677662.913899,U02684Y5BGW,NaN,,https://doi.org/10.1101/2024.04.08.588465,10.1101/2024.04.08.588465,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
2,https://www.biorxiv.org/content/10.1101/2024.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1712677662.913899,U02684Y5BGW,NaN,,https://doi.org/10.1101/2024.04.08.588465,10.1101/2024.04.08.588465,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
3,https://www.biorxiv.org/content/10.1101/2024.1...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1732997414.424169,U02684Y5BGW,NaN,,https://doi.org/10.1101/2024.11.29.625997,10.1101/2024.11.29.625997,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
4,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1643374186.531939,U02684Y5BGW,NaN,,https://doi.org/10.1101/2022.01.26.477951,10.1101/2022.01.26.477951,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."

In [13]:
df_out.to_csv('./df_out.csv', index=False)

In [1]:
import pandas as pd

df_out = pd.read_csv('./df_out.csv')
df_out.head(40)

,url,file,message_index,ts,user,http_status,final_url,doi_links,dois,source_hint,fetch_error
0,https://arxiv.org/abs/2409.00034,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.725700e+09,U029THP4J8Y,200.0,https://arxiv.org/abs/2409.00034,"https://doi.org/10.1021/acssynbio.5c00099,http...","10.1021/acssynbio.5c00099,10.48550/arXiv.2409....",found_in_meta;found_in_doi_link,NaN
1,https://www.biorxiv.org/content/10.1101/2024.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.712678e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2024.04.08.588465,10.1101/2024.04.08.588465,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
2,https://www.biorxiv.org/content/10.1101/2024.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.712678e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2024.04.08.588465,10.1101/2024.04.08.588465,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
3,https://www.biorxiv.org/content/10.1101/2024.1...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.732997e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2024.11.29.625997,10.1101/2024.11.29.625997,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
4,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.643374e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.01.26.477951,10.1101/2022.01.26.477951,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
5,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.643374e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.01.26.477951,10.1101/2022.01.26.477951,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
6,https://www.biorxiv.org/content/10.1101/2022.1...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.669627e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.11.27.518074,10.1101/2022.11.27.518074,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
7,https://www.biorxiv.org/content/10.1101/2022.1...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.669627e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.11.27.518074,10.1101/2022.11.27.518074,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
8,https://www.biorxiv.org/content/10.1101/2022.1...,/Users/corentinbriat/Downloads/Seminar on Biol...,1,1.669669e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.11.28.518161,10.1101/2022.11.28.518161,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
9,https://www.biorxiv.org/content/10.1101/2022.1...,/Users/corentinbriat/Downloads/Seminar on Biol...,1,1.669669e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.11.28.518161,10.1101/2022.11.28.518161,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
10,https://arxiv.org/abs/2302.12521,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.689154e+09,U02684Y5BGW,200.0,https://arxiv.org/abs/2302.12521,"https://doi.org/10.1098/rsif.2023.0244,https:/...","10.1098/rsif.2023.0244,10.48550/arXiv.2302.12521",found_in_meta;found_in_doi_link,NaN
11,https://arxiv.org/abs/2302.12521|https://arxiv...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.689154e+09,U02684Y5BGW,404.0,https://arxiv.org/abs/2302.12521%7Chttps://arx...,NaN,NaN,arxiv_no_doi_expected,NaN
12,https://www.biorxiv.org/content/10.1101/2024.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.732637e+09,U07CPGL4CRZ,NaN,NaN,https://doi.org/10.1101/2024.03.25.586624,10.1101/2024.03.25.586624,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
13,https://www.biorxiv.org/content/10.1101/2024.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.732637e+09,U07CPGL4CRZ,NaN,NaN,https://doi.org/10.1101/2024.03.25.586624,10.1101/2024.03.25.586624,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
14,https://www.nature.com/articles/s41586-022-044...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.646325e+09,U02684Y5BGW,200.0,https://www.nature.com/articles/s41586-022-044...,"https://doi.org/10.1038/s41586-022-04470-1,htt...","10.1038/s41586-022-04470-1,10.1038/s41586-022-...",found_in_meta;found_in_doi_link;found_in_jsonld,NaN
15,https://www.nature.com/articles/s41586-022-044...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.646325e+09,U02684Y5BGW,400.0,https://www.nature.com/articles/s41586-022-044...,NaN,NaN,NaN,NaN
16,https://www.sciencedirect.com/science/article/...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.649341e+09,U02684Y5BGW,403.0,https://www.sciencedirect.com/science/article/...,NaN,NaN,NaN,403 Forbidden (site may block automated requests)
17,https://www.sciencedirect.com/science/article/...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.649341e+09,U02684Y5BGW,403.0,https://www.sciencedirect.com/science/article/...,NaN,NaN,NaN,403 Forbidden (site may block automated requests)
18,https://www.nature.com/articles/s41586-024-079...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.726093e+09,U07CPGL4CRZ,200.0,https://www.nature.com/articles/s41586-024-079...,"https://doi.org/10.1038/s41586-024-07935-7,htt...","10.1038/s41586-024-07935-7,10.5281/zenodo.1271...",found_in_meta;found_in_doi_link;found_in_jsonld,NaN
19,https://www.nature.com/articles/s41586-024-079...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.726093e+09,U07CPGL4CRZ,400.0,https://www.nature.com/articles/s41586-024-079...,NaN,NaN,NaN,NaN
20,https://www.nature.com/articles/s41578-020-002...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.643858e+09,U02684Y5BGW,200.0,https://www.nature.com/articles/s41578-020-002...,"https://doi.org/10.1038/s41578-020-00265-w,htt...","10.1038/s41578-020-00265-w,10.1101/2019.12.20....",found_in_meta;found_in_doi_link;found_in_jsonld,NaN
21,https://www.nature.com/articles/s41578-020-002...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.643858e+09,U02684Y5BGW,400.0,https://www.nature.com/articles/s41578-020-002...,NaN,NaN,NaN,NaN
22,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.670019e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.03.10.483875,10.1101/2022.03.10.483875,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
23,https://biorxiv.org/cgi/content/short/2024.10....,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.730076e+09,U07CPGL4CRZ,NaN,NaN,NaN,NaN,NaN,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
24,https://biorxiv.org/cgi/content/short/2024.10....,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.730076e+09,U07CPGL4CRZ,NaN,NaN,NaN,NaN,NaN,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
25,https://www.sciencedirect.com/science/article/...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.684170e+09,U02684Y5BGW,403.0,https://www.sciencedirect.com/science/article/...,NaN,NaN,NaN,403 Forbidden (site may block automated requests)
26,https://www.sciencedirect.com/science/article/...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.684170e+09,U02684Y5BGW,403.0,https://www.sciencedirect.com/science/article/...,NaN,NaN,NaN,403 Forbidden (site may block automated requests)
27,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.668255e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.03.26.485894v1.fu...,10.1101/2022.03.26.485894v1.full.pdf,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
28,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.668255e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.03.26.485894v1.fu...,10.1101/2022.03.26.485894v1.full.pdf,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
29,https://www.nature.com/articles/s41467-021-238...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.626635e+09,U02684Y5BGW,200.0,https://www.nature.com/articles/s41467-021-238...,"https://doi.org/10.1038/s41467-021-23889-0,htt...","10.1038/s41467-021-23889-0,10.5281/zenodo.4741...",found_in_meta;found_in_doi_link;found_in_jsonld,NaN
30,https://www.nature.com/articles/s41467-021-238...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.626635e+09,U02684Y5BGW,400.0,https://www.nature.com/articles/s41467-021-238...,NaN,NaN,NaN,NaN
31,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.655377e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.06.13.495893,10.1101/2022.06.13.495893,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
32,https://www.biorxiv.org/content/10.1101/2022.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.655377e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2022.06.13.495893,10.1101/2022.06.13.495893,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."
33,https://www.sciencedirect.com/science/article/...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.700211e+09,U029THP4J8Y,403.0,https://www.sciencedirect.com/science/article/...,NaN,NaN,NaN,403 Forbidden (site may block automated requests)
34,https://www.nature.com/articles/s41467-022-348...,/Users/corentinbriat/Downloads/Seminar on Biol...,1,1.700218e+09,U029THP4J8Y,200.0,https://www.nature.com/articles/s41467-022-348...,"https://doi.org/10.1038/s41467-022-34857-7,htt...","10.1038/s41467-022-34857-7,10.1016%2Fj.cell.20...",found_in_meta;found_in_doi_link;found_in_jsonld,NaN
35,https://www.cell.com/biophysj/fulltext/S0006-3...,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.714057e+09,U02684Y5BGW,403.0,https://www.cell.com/biophysj/fulltext/S0006-3...,NaN,NaN,NaN,403 Forbidden (site may block automated requests)
36,https://www.cell.com/biophysj/fulltext/S0006-3495,/Users/corentinbriat/Downloads/Seminar on Biol...,0,1.714057e+09,U02684Y5BGW,403.0,https://www.cell.com/biophysj/fulltext/S0006-3495,NaN,NaN,NaN,403 Forbidden (site may block automated requests)
37,https://www.nature.com/articles/s41467-024-451...,/Users/corentinbriat/Downloads/Seminar on Biol...,1,1.714074e+09,U02684Y5BGW,200.0,https://www.nature.com/articles/s41467-024-451...,"https://doi.org/10.1038/s41467-024-45186-2,htt...","10.1038/s41467-024-45186-2,10.5281/zenodo.8359...",found_in_meta;found_in_doi_link;found_in_jsonld,NaN
38,https://www.nature.com/articles/s41467-024-451...,/Users/corentinbriat/Downloads/Seminar on Biol...,1,1.714074e+09,U02684Y5BGW,400.0,https://www.nature.com/articles/s41467-024-451...,NaN,NaN,NaN,NaN
39,https://www.biorxiv.org/content/10.1101/2024.0...,/Users/corentinbriat/Downloads/Seminar on Biol...,2,1.714096e+09,U02684Y5BGW,NaN,NaN,https://doi.org/10.1101/2024.04.19.590281,10.1101/2024.04.19.590281,found_in_url,"HTTPSConnectionPool(host='www.biorxiv.org', po..."

In [ ]:
# # We get all dois
# import numpy as np


# all_dois = []
# all_doistxt = ''

# for idx, row in df_out.iterrows():
#     print(idx,row['doi_links'])
#     temp_ = row['doi_links']
    
#     if str(temp_) != 'nan':
#         all_dois.append(row['doi_links'].replace(';', ', '))
#         if idx==0:
#             all_doistxt = row['doi_links'].replace(';', ', ')
#         else:
#             all_doistxt = all_doistxt + ', ' + row['doi_links'].replace(';', ', ')
#     # dois = row['dois'].replace(';', ',')

# all_doistxt
# with open("all.txt", "w") as text_file:
#     text_file.write(all_doistxt)

0 https://doi.org/10.1021/acssynbio.5c00099,https://doi.org/10.48550/arXiv.2409.00034
1 https://doi.org/10.1101/2024.04.08.588465
2 https://doi.org/10.1101/2024.04.08.588465
3 https://doi.org/10.1101/2024.11.29.625997
4 https://doi.org/10.1101/2022.01.26.477951
5 https://doi.org/10.1101/2022.01.26.477951
6 https://doi.org/10.1101/2022.11.27.518074
7 https://doi.org/10.1101/2022.11.27.518074
8 https://doi.org/10.1101/2022.11.28.518161
9 https://doi.org/10.1101/2022.11.28.518161
10 https://doi.org/10.1098/rsif.2023.0244,https://doi.org/10.48550/arXiv.2302.12521
11 nan
12 https://doi.org/10.1101/2024.03.25.586624
13 https://doi.org/10.1101/2024.03.25.586624
14 https://doi.org/10.1038/s41586-022-04470-1,https://doi.org/10.1038/s41586-022-04655-8,https://doi.org/10.2210/pdb7S4U/pdb,https://doi.org/10.2210/pdb7S4V/pdb,https://doi.org/10.2210/pdb7S4X/pdb,https://doi.org/10.7554%2FeLife.00471,https://doi.org/10.1126%2Fscience.1231143,https://doi.org/10.1038%2Fnbt.2623,https://doi.org/10.1038%2Fs41586-020-1978-5,https://doi.org/10.1038%2Fs41467-020-17411-1,https://doi.org/10.1146%2Fannurev-biochem-013118-111730,https://doi.org/10.1016%2Fj.sbi.2021.03.004,https://doi.org/10.1038%2Fnature16526,https://doi.org/10.1038%2Fnature24268,https://doi.org/10.1126%2Fscience.aad5227,https://doi.org/10.1038%2Fs41587-020-0537-9,https://doi.org/10.1038%2Fnature15544,https://doi.org/10.1038%2Fs41594-018-0051-7,https://doi.org/10.1126%2Fscience.aad8282,https://doi.org/10.1038%2Fnature13579,https://doi.org/10.1038%2Fnprot.2013.143,https://doi.org/10.1126%2Fsciadv.aao0027,https://doi.org/10.1038%2Fs41594-019-0258-2,https://doi.org/10.1101/2021.09.06.459219,https://doi.org/10.1101/2021.09.16.460614,https://doi.org/10.1038%2Fs41587-020-0646-5,https://doi.org/10.1021%2Facs.jcim.8b00988,https://doi.org/10.1038%2Fs41929-020-00506-9,https://doi.org/10.1126%2Fscience.1247997,https://doi.org/10.1073%2Fpnas.90.14.6498,https://doi.org/10.1021%2Facscatal.0c03566,https://doi.org/10.1093%2Fnar%2Fgkab1072,https://doi.org/10.1016%2Fj.celrep.2017.12.041,https://doi.org/10.1016%2Fj.molcel.2019.09.025,https://doi.org/10.1016%2Fj.cell.2014.02.001,https://doi.org/10.1038%2Fnbt.3117,https://doi.org/10.1038%2Fnbt.2916,https://doi.org/10.1016%2Fj.ab.2021.114239,https://doi.org/10.1016%2Fj.jsb.2005.07.007,https://doi.org/10.1038%2Fnmeth.4169,https://doi.org/10.1038%2Fs41592-020-00990-8,https://doi.org/10.1002%2Fpro.3943,https://doi.org/10.1107%2FS2052252519007619,https://doi.org/10.1107%2FS2059798318002425,https://doi.org/10.1038%2Fs41594-021-00632-3,https://doi.org/10.1038%2Fs41467-020-19072-6,https://doi.org/10.1016%2Fj.cell.2015.08.007,https://doi.org/10.1007/s00203-025-04687-4,https://doi.org/10.1186/s13059-025-03521-w,https://doi.org/10.1038/s41392-025-02147-5,https://doi.org/10.1038/s41467-025-57455-9,https://doi.org/10.1038/s41587-024-02255-7
15 nan
16 nan
17 nan
18 https://doi.org/10.1038/s41586-024-07935-7,https://doi.org/10.5281/zenodo.12713840,https://doi.org/10.3390%2Fproteomes8030014,https://doi.org/10.1038%2Fs41587-020-0570-8,https://doi.org/10.1038%2Fs41557-023-01322-x,https://doi.org/10.1038%2Fnmeth.2369,https://doi.org/10.1016%2Fj.febslet.2013.01.047,https://doi.org/10.1038%2F47412,https://doi.org/10.1038%2Fnature08102,https://doi.org/10.1038%2Fs41565-018-0236-6,https://doi.org/10.1038%2Fs41592-021-01143-1,https://doi.org/10.1038/nbt.4278,https://doi.org/10.1038%2Fnbt.4278,https://doi.org/10.1126%2Fscience.abo7651,https://doi.org/10.1002%2Fadma.202314319,https://doi.org/10.1038%2Fnbt.3423,https://doi.org/10.1126%2Fsciadv.aax8978,https://doi.org/10.1016%2Fj.bbamem.2021.183644,https://doi.org/10.1039%2FC8CS00106E,https://doi.org/10.1021%2Facs.nanolett.9b03134,https://doi.org/10.1021%2Facssensors.7b00362,https://doi.org/10.1021%2Facsnano.9b05156,https://doi.org/10.1038%2Fnnano.2016.267,https://doi.org/10.1038%2Fnnano.2012.24,https://doi.org/10.1021%2Facsnano.7b01212,https://doi.org/10.1038%2Fs41587-019-0345-2,https://doi.org/10.1038%2Fs41467-021-26046-9,https://doi.org/10.1016%2Fj.bios.2021.113108,https://doi.org/10.1038%2Fnnano.2016.120,https://doi.org/10.1021%2Facsnano.6b08452,https://doi.org/10.1038/nbt.4316,https://doi.org/10.1038%2Fnbt.4316,https://doi.org/10.1073%2Fpnas.1312739110,https://doi.org/10.1038%2Fnbt.2799,https://doi.org/10.1021%2Facs.nanolett.2c01338,https://doi.org/10.1038%2Fs41565-023-01462-8,https://doi.org/10.1038/s41587-023-01839-z,https://doi.org/10.1038%2Fs41587-023-01839-z,https://doi.org/10.1021%2Facs.nanolett.1c02371,https://doi.org/10.1126%2Fscience.abl4381,https://doi.org/10.1039%2FD1SC04342K,https://doi.org/10.1016%2Fj.isci.2021.103032,https://doi.org/10.1038%2Fnature13768,https://doi.org/10.1016%2Fj.chembiol.2009.05.007,https://doi.org/10.1038%2Fnbt.2503,https://doi.org/10.1021%2Fnn5049987,https://doi.org/10.1038%2Fs41557-021-00824-w,https://doi.org/10.1110%2Fps.0237603,https://doi.org/10.1038%2Fs41587-021-01002-6,https://doi.org/10.7554%2FeLife.52774,https://doi.org/10.1126%2Fscience.aav0725,https://doi.org/10.1016%2Fj.cell.2018.09.022,https://doi.org/10.1038%2Fs41586-022-05575-3,https://doi.org/10.1016%2FS0021-9258%2817%2940329-2,https://doi.org/10.1016%2FS0092-8674%2803%2900612-3,https://doi.org/10.1016%2Fj.cell.2011.04.010,https://doi.org/10.1016%2Fj.bpj.2013.04.056,https://doi.org/10.1073%2Fpnas.1707207115,https://doi.org/10.1038/s41587-022-01598-3,https://doi.org/10.1038%2Fs41587-022-01598-3,https://doi.org/10.3390%2Fmolecules26123521,https://doi.org/10.1038%2Fnchem.2888,https://doi.org/10.1038%2Fnnano.2010.177,https://doi.org/10.1038%2Fnature04031,https://doi.org/10.18637%2Fjss.v031.i07,https://doi.org/10.1146%2Fannurev.bb.13.060184.001045,https://doi.org/10.1101/014258,https://doi.org/10.1038%2Fnature03528,https://doi.org/10.1016%2Fj.cell.2013.09.022,https://doi.org/10.5281/zenodo.1271384060,https://doi.org/10.1038/s41576-025-00915-1,https://doi.org/10.1038/s44221-025-00571-z,https://doi.org/10.1038/s41571-025-01110-1,https://doi.org/10.1038/s41467-025-64025-6,https://doi.org/10.1038/s41467-025-58509-8
19 nan
20 https://doi.org/10.1038/s41578-020-00265-w,https://doi.org/10.1101/2019.12.20.882472,https://doi.org/10.1016/j.matt.2020.09.006,https://doi.org/10.1016%2Fj.matt.2020.09.006,https://doi.org/10.1038/s41587-020-0584-2,https://doi.org/10.1038%2Fs41587-020-0584-2,https://doi.org/10.1186/s12866-025-04142-w,https://doi.org/10.1186/s12951-025-03254-9,https://doi.org/10.1038/s41467-024-55097-x,https://doi.org/10.1038/s41587-024-02194-3,https://doi.org/10.1038/s43246-025-00969-y
21 nan
22 https://doi.org/10.1101/2022.03.10.483875
23 nan
24 nan
25 nan
26 nan
27 https://doi.org/10.1101/2022.03.26.485894v1.full.pdf
28 https://doi.org/10.1101/2022.03.26.485894v1.full.pdf
29 https://doi.org/10.1038/s41467-021-23889-0,https://doi.org/10.5281/zenodo.4741005,https://doi.org/10.1038%2Fncomms14366,https://doi.org/10.1128%2FMCB.25.18.8239-8250.2005,https://doi.org/10.4161%2Ffly.6311,https://doi.org/10.1091%2Fmbc.E15-07-0512,https://doi.org/10.1038%2Fsrep31774,https://doi.org/10.1038%2Fs41598-017-14330-y,https://doi.org/10.1002%2Fbiot.201200085,https://doi.org/10.1016%2FB978-0-12-385075-1.00007-X,https://doi.org/10.1074%2Fjbc.272.41.25641,https://doi.org/10.1038%2Fnbt.4111,https://doi.org/10.1371%2Fjournal.pcbi.1004958,https://doi.org/10.1371%2Fjournal.pcbi.1001101,https://doi.org/10.1038%2Fmsb.2011.49,https://doi.org/10.1093%2Fnar%2Fgky795,https://doi.org/10.1038%2Fs41467-020-19126-9,https://doi.org/10.1126%2Fscience.1190544,https://doi.org/10.1038%2Fncomms12959,https://doi.org/10.7554%2FeLife.12175,https://doi.org/10.1038%2Fnbt1307,https://doi.org/10.1038%2Fnnano.2010.135,https://doi.org/10.15252%2Fmsb.20167265,https://doi.org/10.1038%2Fmtna.2015.23,https://doi.org/10.1016%2Fj.bpj.2013.01.013,https://doi.org/10.1002%2Fj.1460-2075.1994.tb06337.x,https://doi.org/10.1371%2Fjournal.pone.0018556,https://doi.org/10.1073%2Fpnas.0809901106,https://doi.org/10.1038%2Fncomms2471,https://doi.org/10.1038%2Fs41467-019-10330-w,https://doi.org/10.1016%2FS0168-1656%2802%2900130-X,https://doi.org/10.1371%2Fjournal.pcbi.1002074,https://doi.org/10.1002%2Fbiot.201800219,https://doi.org/10.1016%2Fj.jconrel.2008.12.016,https://doi.org/10.1126%2Fscience.1070919,https://doi.org/10.1038%2Fnature03998,https://doi.org/10.1038%2Fnmeth.4074,https://doi.org/10.1074%2Fjbc.M102815200,https://doi.org/10.1038%2Fnmeth.4509,https://doi.org/10.1038%2Fnmeth.3891,https://doi.org/10.1021%2Facssensors.8b00473,https://doi.org/10.1371%2Fjournal.pone.0123562,https://doi.org/10.1046%2Fj.1432-1327.2000.01645.x,https://doi.org/10.1038%2F313812a0,https://doi.org/10.1016%2F0167-4781%2888%2990084-X,https://doi.org/10.1128%2FJVI.74.10.4512-4522.2000,https://doi.org/10.1128%2FMCB.21.10.3576-3588.2001,https://doi.org/10.1128%2FJVI.01606-13,https://doi.org/10.1128%2FJVI.79.21.13497-13508.2005,https://doi.org/10.1016%2FS0378-1119%2800%2900242-0,https://doi.org/10.1016%2Fj.heliyon.2020.e03504,https://doi.org/10.1038%2Fsj.gt.3300363,https://doi.org/10.1111%2Fj.1365-2516.2006.01274.x,https://doi.org/10.2217%2F17460751.4.2.239,https://doi.org/10.1089%2Fhum.1997.8.17-2007,https://doi.org/10.1038%2Fsrep16952,https://doi.org/10.1371%2Fjournal.pcbi.1002672,https://doi.org/10.1093%2Fnar%2Fgkaa668,https://doi.org/10.1006%2Fmthe.2000.0050,https://doi.org/10.1038%2Fs41467-020-18392-x,https://doi.org/10.1016%2Fj.isci.2018.07.006,https://doi.org/10.1038%2Fs41592-019-0582-9,https://doi.org/10.1093%2Fbioinformatics%2Fbtr401,https://doi.org/10.1038/s41587-025-02854-y
30 nan
31 https://doi.org/10.1101/2022.06.13.495893
32 https://doi.org/10.1101/2022.06.13.495893
33 nan
34 https://doi.org/10.1038/s41467-022-34857-7,https://doi.org/10.1016%2Fj.cell.2015.11.018,https://doi.org/10.1038%2Fs41586-019-0969-x,https://doi.org/10.1073%2Fpnas.1912459116,https://doi.org/10.1038%2Fsj.bjp.0707307,https://doi.org/10.1016%2Fj.ejphar.2009.06.065,https://doi.org/10.1073/pnas.1417811112,https://doi.org/10.1021%2Facs.jmedchem.7b00681,https://doi.org/10.1073%2Fpnas.2024725118,https://doi.org/10.1063%2F1.4960505,https://doi.org/10.1371%2Fjournal.pcbi.1006365,https://doi.org/10.1155%2F2020%2F8536365,https://doi.org/10.1371%2Fjournal.pcbi.1003650,https://doi.org/10.1093%2Fbioinformatics%2Fbtm453,https://doi.org/10.1093%2Fbioinformatics%2Fbtp616,https://doi.org/10.1002%2F1873-3468.12684,https://doi.org/10.15252%2Fmsb.20188746,https://doi.org/10.1073%2Fpnas.84.20.7024,https://doi.org/10.1006%2Ftpbi.1995.1027,https://doi.org/10.1103%2FPhysRevE.79.031911,https://doi.org/10.1073%2Fpnas.1612651113,https://doi.org/10.1103%2FPhysRevLett.118.268101,https://doi.org/10.1093%2Fnar%2Fgky382,https://doi.org/10.1101/717199,https://doi.org/10.1073%2Fpnas.1910888117,https://doi.org/10.1073%2Fpnas.151588598,https://doi.org/10.1126%2Fscience.1070919,https://doi.org/10.1073%2Fpnas.162041399,https://doi.org/10.1016%2Fj.cell.2008.09.050,https://doi.org/10.1073%2Fpnas.1018832108,https://doi.org/10.1038%2Fs41586-018-0414-6,https://doi.org/10.1016%2Fj.cell.2018.05.035,https://doi.org/10.1016%2Fj.cell.2005.09.031,https://doi.org/10.2307%2F3212214,https://doi.org/10.1016%2F0378-4371%2892%2990283-V,https://doi.org/10.1063%2F1.481811,https://doi.org/10.1146%2Fannurev.physchem.58.032806.104637,https://doi.org/10.1063%2F1.4801941,https://doi.org/10.1126%2Fscience.1242975,https://doi.org/10.1103%2FPhysRevLett.124.108101,https://doi.org/10.1016%2Fj.bpj.2012.07.015,https://doi.org/10.1103%2FPhysRevE.102.022409,https://doi.org/10.1016%2Fj.bpj.2022.02.004,https://doi.org/10.1073%2Fpnas.1213530109,https://doi.org/10.1098%2Frsif.2016.0833,https://doi.org/10.1111%2F1467-9868.00282,https://doi.org/10.1080/01605682.2019.1657368,https://doi.org/10.1103%2FPhysRevE.101.032417,https://doi.org/10.1111%2Fj.1540-6261.1986.tb04523.x,https://doi.org/10.1093%2Frfs%2F3.4.573,https://doi.org/10.1103%2FPhysRevE.86.061910,https://doi.org/10.1371%2Fjournal.pcbi.1003942,https://doi.org/10.1038%2Fs41587-019-0071-9,https://doi.org/10.1038%2Fs41592-019-0690-6,https://doi.org/10.1063%2F1.1731239,https://doi.org/10.1073%2Fpnas.1804060115,https://doi.org/10.1101/2021.07.30.454514,https://doi.org/10.1098%2Frsif.2021.0274,https://doi.org/10.1038%2Fs41586-021-03969-3,https://doi.org/10.1038%2Fs41587-021-00870-2,https://doi.org/10.1101/2022.06.11.495771,https://doi.org/10.1103%2FPhysRevE.89.012713,https://doi.org/10.1002%2Fwrna.1401,https://doi.org/10.1038%2Fs41576-018-0013-2,https://doi.org/10.1111%2F1467-9469.00331,https://doi.org/10.1126%2Fscience.1216379,https://doi.org/10.1038%2Fnsmb.1934,https://doi.org/10.1016%2Fj.molcel.2011.11.035,https://doi.org/10.1101/657619,https://doi.org/10.1016%2F0021-9991%2876%2990041-3,https://doi.org/10.1038%2Fs41586-021-03500-8,https://doi.org/10.1093/bioinformatics/btz279,https://doi.org/10.1038%2Fs41592-019-0686-2,https://doi.org/10.7717%2Fpeerj-cs.55,https://doi.org/10.5281/zenodo.7262328,https://doi.org/10.1038/s41596-024-01057-0,https://doi.org/10.1038/s41592-025-02832-x,https://doi.org/10.1007/s11538-024-01301-4,https://doi.org/10.1007/s11538-023-01213-9
35 nan
36 nan
37 https://doi.org/10.1038/s41467-024-45186-2,https://doi.org/10.5281/zenodo.8359540,https://doi.org/10.5281/zenodo.10370923,https://doi.org/10.1038%2F35020524,https://doi.org/10.1038%2Fs41586-022-04910-y,https://doi.org/10.1038%2Fnatrevmats.2017.68,https://doi.org/10.1038%2Fnnano.2017.127,https://doi.org/10.1038%2Fs41586-022-05218-7,https://doi.org/10.1038%2Fnature10262,https://doi.org/10.1038%2Fnchem.1869,https://doi.org/10.1038%2Fs41557-022-00957-6,https://doi.org/10.1038%2Fs41565-018-0202-3,https://doi.org/10.7554%2FeLife.09771,https://doi.org/10.1073%2Fpnas.1311166110,https://doi.org/10.1126%2Fscience.1255550,https://doi.org/10.1073%2Fpnas.1710620114,https://doi.org/10.1038%2Fnphys3469,https://doi.org/10.1073%2Fpnas.2135496100,https://doi.org/10.1126%2Fscience.aal3059,https://doi.org/10.1126%2Fscience.abb5317,https://doi.org/10.1126%2Fscience.169.3943.392,https://doi.org/10.3389%2Ffmicb.2020.624830,https://doi.org/10.1146%2Fannurev-genet-072220-033342,https://doi.org/10.1038%2Fs41467-020-19395-4,https://doi.org/10.1073%2Fpnas.0700672104,https://doi.org/10.7554%2FeLife.01775,https://doi.org/10.1002%2Fanie.200806070,https://doi.org/10.1038%2Fs41467-019-10647-6,https://doi.org/10.1021%2Facssynbio.5b00296,https://doi.org/10.1038%2Fs41592-021-01341-x,https://doi.org/10.1021%2Fjacs.1c05004,https://doi.org/10.1038%2Fnmeth.4509,https://doi.org/10.1038/s41598-019-48468-8,https://doi.org/10.1002%2Fbit.20529,https://doi.org/10.1073%2Fpnas.56.6.1770,https://doi.org/10.1016%2Fj.cell.2014.05.038,https://doi.org/10.1038%2Fncomms13788,https://doi.org/10.1038%2F35051126,https://doi.org/10.1073%2Fpnas.96.25.14342,https://doi.org/10.1073%2Fpnas.84.20.7024,https://doi.org/10.1371%2Fjournal.pcbi.1000109,https://doi.org/10.1016%2Fj.bpj.2019.04.023,https://doi.org/10.1126%2Fscience.1119623,https://doi.org/10.1016%2Fj.cell.2005.09.031,https://doi.org/10.1021%2Fbi980152v,https://doi.org/10.1038%2Fs41467-022-32829-5,https://doi.org/10.1016%2Fj.molcel.2016.06.006,https://doi.org/10.1021%2Facssynbio.1c00430,https://doi.org/10.1038%2Fs41467-020-14694-2,https://doi.org/10.1021%2Fjacs.3c01375,https://doi.org/10.1038%2Fs41467-020-20180-6,https://doi.org/10.1073%2Fpnas.0408236101,https://doi.org/10.1038%2Fs41565-020-0720-7,https://doi.org/10.1021%2Fbi00027a005,https://doi.org/10.1016%2F0022-2836%2887%2990517-1,https://doi.org/10.1107%2FS1744309106051530,https://doi.org/10.1021%2Facs.nanolett.7b01009,https://doi.org/10.1038%2Fnmeth.3143,https://doi.org/10.1038%2Fnprot.2017.024,https://doi.org/10.1038%2Fnmeth.2071,https://doi.org/10.1006%2Fjcis.1996.0217,https://doi.org/10.1126%2Fscience.1202142,https://doi.org/10.1016%2FS0092-8674%2801%2900286-0,https://doi.org/10.1038/s41467-025-65249-2
38 nan
39 https://doi.org/10.1101/2024.04.19.590281
40 https://doi.org/10.1101/2024.04.19.590281
41 https://doi.org/10.1101/2024.03.20.585869
42 https://doi.org/10.1101/2024.03.20.585869
43 nan
44 nan
45 https://doi.org/10.48550/arXiv.2309.07386
46 nan
47 nan
48 https://doi.org/10.1101/2022.11.02.514931
49 https://doi.org/10.1101/2022.11.02.514931
50 https://doi.org/10.1038/s41467-022-34232-6,https://doi.org/10.1016%2Fj.mib.2021.05.004,https://doi.org/10.1126%2Fscience.8303295,https://doi.org/10.1016%2Fj.tibs.2016.09.010,https://doi.org/10.1371%2Fjournal.pone.0199432,https://doi.org/10.1021%2Facssynbio.0c00296,https://doi.org/10.15252%2Fmsb.20188719,https://doi.org/10.1002%2Fcbic.201900272,https://doi.org/10.1002%2Fanie.201505664,https://doi.org/10.1016%2Fj.bbrc.2016.09.005,https://doi.org/10.1038%2Fnbt1413,https://doi.org/10.1002%2Fpro.5560041120,https://doi.org/10.1126%2Fscience.1068539,https://doi.org/10.1038%2Fnmeth819,https://doi.org/10.1038%2Fs41592-019-0352-8,https://doi.org/10.1038%2Fsrep38828,https://doi.org/10.1038%2Fs42003-020-01127-5,https://doi.org/10.1371%2Fjournal.pone.0023126,https://doi.org/10.1016%2Fj.ab.2009.04.029,https://doi.org/10.1016%2Fj.jprot.2012.06.020,https://doi.org/10.1016%2Fj.cell.2014.02.033,https://doi.org/10.1021%2Facssynbio.6b00072,https://doi.org/10.1016%2Fj.femsle.2005.05.051,https://doi.org/10.3390%2Fijms21239217,https://doi.org/10.1128%2FJB.00615-07,https://doi.org/10.1016%2FS0006-3495%2898%2977870-1,https://doi.org/10.1038%2Fsrep28166,https://doi.org/10.15252%2Fmsb.20156178,https://doi.org/10.1038%2Fnmeth.3339,https://doi.org/10.1016%2Fj.coisb.2019.03.001,https://doi.org/10.1038%2Fnmeth.3100,https://doi.org/10.1021%2Fsb400203p,https://doi.org/10.1038%2Fnmeth.3891,https://doi.org/10.1038%2Fnrmicro1820,https://doi.org/10.1021%2Facs.bioconjchem.8b00180,https://doi.org/10.1002%2Fcbic.202000203,https://doi.org/10.1021%2Fsb400089c,https://doi.org/10.1021%2Facssynbio.7b00237,https://doi.org/10.1038%2Fnbt1037,https://doi.org/10.1016%2F0378-1119%2895%2900685-0,https://doi.org/10.1371%2Fjournal.pone.0028674,https://doi.org/10.1093%2Fnar%2Fgks1119,https://doi.org/10.1016%2Fj.tcb.2007.02.001,https://doi.org/10.17504/protocols.io.bzudp6s6,https://doi.org/10.17504/protocols.io.bztsp6ne,https://doi.org/10.17504/protocols.io.bzt6p6re,https://doi.org/10.5281/zenodo.5760028,https://doi.org/10.1038/s41586-024-08501-x,https://doi.org/10.1186/s12934-024-02386-1,https://doi.org/10.1038/s41467-024-50566-9
51 nan
52 https://doi.org/10.1101/2021.12.31.474658
53 https://doi.org/10.1101/2021.12.31.474658

In [16]:
# We get first dois

first_dois = []
first_doistxt = ''

for idx, row in df_out.iterrows():
    # print(row['doi_links'], '|', row['doi_links'].split(',')[0], '\n')
    # print(row['url'].split('|')[0])

    # print(idx,row['url'])
    temp_ = row['url']
    
    if str(temp_) != 'nan':

        url_ = row['url'].split('|')[0]
        # url_ = row['final_url'].split('%')[0].split('?')[0]

        if 'arxiv.org' in url_:
            first_dois.append(url_)
            first_doi = url_
        else:
            # print(idx, row['doi_links'])
            temp_ = row['doi_links']

            if str(temp_) != 'nan':
                first_doi = row['doi_links'].split(',')[0]
                first_dois.append(first_doi)
        
        if len(first_doi)>0:
            if len(first_doistxt)==0:
                first_doistxt = first_doi
            else:
                first_doistxt = first_doistxt + ', ' + first_doi
        # dois = row['dois'].replace(';', ',')

first_doistxt
with open("first.txt", "w") as text_file:
    text_file.write(first_doistxt)

In [ ]:
arxiv_urls = []
arxiv_urlstxt = ''
for idx, row in df_out.iterrows():
    url_ = row['final_url'].split('%')[0].split('?')[0]
    if 'arxiv.org' in url_:
        # print(url_)
        if len(arxiv_urlstxt)==0:
            arxiv_urlstxt = url_
        else:
            arxiv_urlstxt = arxiv_urlstxt + ', ' + url_

    # for url_ in url_tab:
    #     if 'arxiv.org' in url_:
    #         if len(all_urlstxt)==0:
    #             all_urlstxt = url_
    #         else:
    #             all_urlstxt = url_ + ', ' + url_

# all_doistxt
with open("arxiv.txt", "w") as text_file:
    text_file.write(arxiv_urlstxt)

In [ ]:
if not df_out.empty:
    has_doi = df_out["dois"].fillna("").str.len() > 0
    print("Rows with DOI:", int(has_doi.sum()), "/", len(df_out))
    print("Unique URLs with DOI:", df_out.loc[has_doi, "url"].nunique(), "/", df_out["url"].nunique())
    df_out.loc[~has_doi, ["url","http_status","fetch_error","source_hint"]].head(20)